#!/bin/bash

echo -e " - Untracked files to be removed -\n"

git clean -xdn

if [ "$1" == "dev" ]; then
	echo "Would remove package-lock.json"
fi

if [ -e "$(which ncu)" ]; then
	echo -e "\n - Packages that can be updated -\n"

	ncu

	echo -e "\n[enter] to continue. [y + enter] to update package versions and continue."

	read -p "" answer

	if [ "$answer" == "y" ]; then
		echo -e "\nUpdating package.json\n"

		ncu -u
	fi
fi

if [ "$1" == "dev" ]; then
	echo -e "Removing package-lock.json\n"

	rm -f ./package-lock.json
fi

git clean -xdf

echo -e "\nInstalling packages"

if [ ! -e "$(which zelda)" ]; then
	npm i -g fatlard1993/zelda
fi

if [ "$1" == "dev" ]; then
	zelda -ia
else
	npm i --only=prod
fi