// includes keyboard
// babel
/* global SoftKeyboard */

SoftKeyboard.setKeyDefinitions({
	esc: { key: 'escape', text: 'Esc' },
	backspace: { text: '' },
	tab: { text: '' },
	delete: { text: '' },
	space: { text: '' },
	settings: { text: '' },
	mouse: { text: '' },
	hide: { text: '' },
	lmb: { text: '' },
	rmb: { text: '' },
	home: { text: '' },
	left: { text: '' },
	up: { text: '' },
	down: { text: '' },
	right: { text: '' },
	end: { text: 'End' },
	shift: { class: 'mod', text: '' },
	fakeShift: { class: 'shift', text: '' },
	ctrl: { key: 'control', text: 'Ctrl', class: 'mod' },
	os: { key: 'command', class: 'mod os', text: '' },
	alt: { class: 'mod', text: 'Alt' },
	return: { key: 'enter', class: 'return', text: '' },
	pgUp: { key: 'pageup', text: '' },
	pgDown: { key: 'pagedown', text: '' },
	volUp: { key: 'audio_vol_up', text: '' },
	volDown: { key: 'audio_vol_down', text: '' },
	volMute: { key: 'audio_mute', text: '' },
	play: { key: 'audio_play', text: '' },
	pause: { key: 'audio_pause', text: '' },
	stop: { key: 'audio_stop', text: '' },
	next: { key: 'audio_next', text: '' },
	prev: { key: 'audio_prev', text: '' },
	keyboard: { key: 'basic', class: 'keyboard', text: '' },
	'!': { mod: 'shift', key: '1' },
	'@': { mod: 'shift', key: '2' },
	'#': { mod: 'shift', key: '3' },
	'$': { mod: 'shift', key: '4' },
	'%': { mod: 'shift', key: '5' },
	'^': { mod: 'shift', key: '6' },
	'&': { mod: 'shift', key: '7' },
	'*': { mod: 'shift', key: '8' },
	'(': { mod: 'shift', key: '9' },
	')': { mod: 'shift', key: '0' },
	'~': { mod: 'shift', key: '`' },
	'_': { mod: 'shift', key: '-' },
	'+': { mod: 'shift', key: '=' },
	'{': { mod: 'shift', key: '[' },
	'}': { mod: 'shift', key: ']' },
	'|': { mod: 'shift', key: '\\' },
	':': { mod: 'shift', key: ';' },
	'"': { mod: 'shift', key: `'` },
	'<': { mod: 'shift', key: ',' },
	'>': { mod: 'shift', key: '.' },
	'?': { mod: 'shift', key: '/' },
	'Q': { mod: 'shift', key: 'q' },
	'W': { mod: 'shift', key: 'w' },
	'E': { mod: 'shift', key: 'e' },
	'R': { mod: 'shift', key: 'r' },
	'T': { mod: 'shift', key: 't' },
	'Y': { mod: 'shift', key: 'y' },
	'U': { mod: 'shift', key: 'u' },
	'I': { mod: 'shift', key: 'i' },
	'O': { mod: 'shift', key: 'o' },
	'P': { mod: 'shift', key: 'p' },
	'A': { mod: 'shift', key: 'a' },
	'S': { mod: 'shift', key: 's' },
	'D': { mod: 'shift', key: 'd' },
	'F': { mod: 'shift', key: 'f' },
	'G': { mod: 'shift', key: 'g' },
	'H': { mod: 'shift', key: 'h' },
	'J': { mod: 'shift', key: 'j' },
	'K': { mod: 'shift', key: 'k' },
	'L': { mod: 'shift', key: 'l' },
	'Z': { mod: 'shift', key: 'z' },
	'X': { mod: 'shift', key: 'x' },
	'C': { mod: 'shift', key: 'c' },
	'V': { mod: 'shift', key: 'v' },
	'B': { mod: 'shift', key: 'b' },
	'N': { mod: 'shift', key: 'n' },
	'M': { mod: 'shift', key: 'm' }
});

SoftKeyboard.setLayouts({
	full: [
		['media', 'numpad', 'basic', 'full', 'mouse', 'hide'],
		['esc', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f8', 'f9', 'f10', 'f11', 'f12', 'delete'],
		['`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'backspace'],
		['tab', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\\'],
		['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', `'`, 'return'],
		['fakeShift', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', 'shift'],
		['ctrl', 'os', 'alt', 'space', 'left', 'up', 'down', 'right']
	],
	fullFakeShift: [
		['media', 'numpad', 'basic', 'full', 'mouse', 'hide'],
		['esc', 'volMute', 'volDown', 'volUp', 'prev', 'play', 'pause', 'next', 'settings', 'f8', 'f9', 'f10', 'f11', 'f12', 'delete'],
		['~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', 'backspace'],
		['tab', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '|'],
		['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"', 'return'],
		['fakeShift', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?', 'shift'],
		['ctrl', 'os', 'alt', 'space', 'home', 'pgUp', 'pgDown', 'end']
	],
	basic: [
		['media', 'numpad', 'basic', 'full', 'mouse', 'hide'],
		['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
		['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
		['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l'],
		['fakeShift', 'z', 'x', 'c', 'v', 'b', 'n', 'm', 'backspace'],
		['os', 'space', 'ctrl'],
		['left', 'up', 'down', 'right']
	],
	basicFakeShift: [
		['media', 'numpad', 'basic', 'full', 'mouse', 'hide'],
		['!', '@', '#', '$', '%', '^', '&', '*', '(', ')'],
		['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
		['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
		['fakeShift', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', 'backspace'],
		['os', 'space', 'ctrl'],
		['left', 'up', 'down', 'right']
	],
	numpad: [
		['media', 'numpad', 'basic', 'full', 'mouse', 'hide'],
		['1', '2', '3', 'backspace', 'delete'],
		['4', '5', '6', '+', '-'],
		['7', '8', '9', '*', '/'],
		['.', '0', ',', 'tab', 'return'],
		['left', 'up', 'down', 'right']
	],
	media: [
		['media', 'numpad', 'basic', 'full', 'mouse', 'hide'],
		['esc', 'volMute', 'volDown', 'volUp'],
		['play', 'pause', 'prev', 'next'],
		['f', 'space', 'f11']
	],
	everything: [
		['esc', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f8', 'f9', 'f10', 'f11', 'f12'],
		['volMute', 'volDown', 'volUp', 'prev', 'play', 'pause', 'next', ':', '"', '<', '>', '?'],
		['`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'delete'],
		['~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', 'backspace'],
		['tab', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\\'],
		['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', `'`, 'return'],
		['fakeShift', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', 'shift'],
		['ctrl', 'os', 'alt', 'space', 'left', 'up', 'down', 'right']
	],
	'abc1': [
		['hide', 'ABC!', 'numbers', 'symbols', 'full', 'mouse'],
		['esc', 'tab', 'delete', 'settings'],
		['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
		['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
		['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l'],
		['shift', 'z', 'x', 'c', 'v', 'b', 'n', 'm', 'backspace'],
		['os', 'space', 'return'],
		['ctrl', 'alt', 'left', 'up', 'down', 'right']
	],
	'ABC!': [
		['abc1', 'hide', 'numbers', 'symbols', 'full', 'mouse'],
		['esc', 'tab', 'delete', 'settings'],
		['!', '@', '#', '$', '%', '^', '&', '*', '(', ')'],
		['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
		['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
		['shift', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', 'backspace'],
		['os', 'space', 'return'],
		['ctrl', 'alt', 'home', 'pgUp', 'pgDown', 'end']
	],
	symbols: [
		['abc1', 'ABC!', 'numbers', 'hide', 'full', 'mouse'],
		['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
		['`', '[', ']', '\\', ';', '\'', ',', '.', '/', '-', '='],
		['~', '{', '}', '|', ':', '"', '<', '>', '?', '_', '+'],
		['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', 'backspace'],
		['delete', 'space', 'return'],
		['tab', 'left', 'up', 'down', 'right']
	],
	numbers: [
		['abc1', 'ABC!', 'hide', 'symbols', 'full', 'mouse'],
		['1', '2', '3', 'backspace'],
		['4', '5', '6', 'delete'],
		['7', '8', '9', '.'],
		['.', '0', '+', '-'],
		['tab', 'space', 'return'],
		['tab', 'left', 'up', 'down', 'right']
	],
	mouse: [
		['lmb', 'rmb'],
		['up', 'keyboard', 'down'],
		['home', 'pgUp', 'pgDown', 'end']
	],
	hide: [
		['keyboard']
	]
});